Name: DeviceSettingsWidget
Id: g=3b54aba68d838998aa9ed471505e7736
Type: FolderType
Children:
- Name: DeviceSettingsWidget
  Id: g=343e9a553a1648e3de95b91f6d877b43
  Supertype: Screen
  ReferenceType: HasComponent
  Children:
  - Name: HorizontalAlignment
    Id: g=b8d23e254a14e1d9f030d116a634c9f7
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
  - Name: VerticalAlignment
    Id: g=81de1187be4ca96fa4df05a82192c907
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
  - Name: Width
    Id: g=1d0412a223029a5f119a3299d149d543
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Height
    Id: g=338d45636c03c665c204805b1a815e38
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 240.0
  - Name: NavigationPanel1
    Id: g=883e0dee6252aa60a5b6f301d5789867
    Type: NavigationPanel
    Children:
    - Name: Panels
      Id: g=0680146c4538de65e00a353c564a6a93
      Type: BaseObjectType
      Children:
      - Name: Panel1
        Id: g=42e26657b2022eb235cf146a0ce2c2f1
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Id: g=7da17efd02f055ae6b3beb93a798e773
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"Configuration"}
        - Name: Panel
          Id: g=41194e983db2501351f554090859b008
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/ElettromeccanicaVeneta_20_01_2025/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Configuration"
          Children:
          - Name: Kind
            Id: g=a0850e0eb69e2562e2d095b698f84de3
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Id: g=394d79f0e89696494666440029b1411b
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Id: g=2adec92a232fc19bc51a5c6930e3ce31
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel2
        Id: g=ebc4f53faa2a08d9d187d62fd19b072d
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Id: g=a43848de68d92919cfcdd7ed3a318b44
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"ProductInformation"}
        - Name: Panel
          Id: g=1b795481af7fc9ad70a4547f65388ab9
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/ElettromeccanicaVeneta_20_01_2025/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Product_Information"
          Children:
          - Name: Kind
            Id: g=28ff4afc6bf32284a9215717610d1f63
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Id: g=8e1fe86cbb5c427658c8a9becc31d5a7
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Id: g=23afee52700f4f6bd44d26eae942d1fc
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel3
        Id: g=324727b54280aa0575ff25ff19f29345
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Id: g=993081e4458a3d498607b2179a0d26f3
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":18,"TextId":"Diagnostics"}
        - Name: Panel
          Id: g=2cae98af7d91d0f64fc6bce12104f150
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/ElettromeccanicaVeneta_20_01_2025/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Diagnostics"
          Children:
          - Name: Kind
            Id: g=d088a9d9499366ecaac66f1cc96b225d
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Id: g=e7f2ee18ba90e9b8e5bb0b086d1bf0be
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Id: g=ad54c192a46053e88d15231a0cf1109d
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
    - Name: CurrentPanel
      Id: g=f61cd5395992d11eb2acdeae25bbc2ec
      Type: NodePointer
      DataType: NodeId
      AccessLevel: Read
      Children:
      - Name: Kind
        Id: g=68dc3a8a0c175079fdcae8b853176e7f
        Type: PropertyType
        DataType: NodeId
        Value: {"Id":6,"Namespace":6}
    - Name: Width
      Id: g=abef0e811284d5f59eeaf1ea6a3db506
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 304.0
    - Name: Height
      Id: g=08f4f69b760ba444724c7c03d2ef48a0
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 240.0
    - Name: HorizontalAlignment
      Id: g=0899198e16e5cc22db36feab7a1c18a9
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: VerticalAlignment
      Id: g=ebbd9c9239f4dbcbf6151a2c758c93fd
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: TopMargin
      Id: g=f9fc3e28a66e1faa40e6bdde537ff609
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: BottomMargin
      Id: g=6fcb060be8569c2dd09d728bcc6cd871
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: CurrentTabIndex
      Id: g=beb84da3e9d35c4a08ceecb626994060
      Type: BaseDataVariableType
      DataType: Int32
    - Class: Reference
      Target: ns=5;i=1181
    - Class: Reference
      Target: ns=5;i=1183
  - Name: SystemNode
    Id: g=7bc5b1dd7ec73ff3f1ebd5607903f3a2
    Type: NodePointer
    DataType: NodeId
    Value: "/Objects/ElettromeccanicaVeneta_20_01_2025/System/System"
    Children:
    - Name: Kind
      Id: g=5693956c2a854f068536ffcd53f6f366
      Type: PropertyType
      DataType: NodeId
      Value: "/Types/ObjectTypes/BaseObjectType/System"
  - Name: DeviceSettingsWidgetLogic
    Id: g=a5ed3d69a9073ee9987755de963d52e4
    Type: NetLogic
- File: DeviceSettingsWidgetComponents/DeviceSettingsWidgetComponents.yaml
